import type * as MonacoEditor from 'monaco-editor';

export const kirunDarkTheme: MonacoEditor.editor.IStandaloneThemeData = {
    base: 'vs-dark',
    inherit: true,
    rules: [
        { token: 'keyword', foreground: 'A78BFA', fontStyle: 'bold' },
        { token: 'keyword.control', foreground: 'FB923C' },
        { token: 'type', foreground: '2DD4BF', fontStyle: 'bold' },
        { token: 'type.identifier', foreground: '2DD4BF', fontStyle: 'bold' },
        { token: 'entity.name.function', foreground: '34D399', fontStyle: 'bold' },
        { token: 'entity.name.tag', foreground: '94A3B8' },
        { token: 'variable.parameter', foreground: '60A5FA' },
        { token: 'variable.predefined', foreground: '22D3EE', fontStyle: 'bold' },
        { token: 'variable', foreground: '93C5FD' },
        { token: 'identifier', foreground: 'e4e4e7' },
        { token: 'number', foreground: 'A3E635' },
        { token: 'number.float', foreground: 'A3E635' },
        { token: 'string.value', foreground: 'FB923C' },
        { token: 'string.expression', foreground: '5EEAD4' },
        { token: 'string', foreground: 'FDBA74' },
        { token: 'string.escape', foreground: 'FACC15' },
        { token: 'string.invalid', foreground: 'F43F5E' },
        { token: 'comment', foreground: '64748B', fontStyle: 'italic' },
        { token: 'operator', foreground: 'e4e4e7' },
        { token: 'delimiter', foreground: 'e4e4e7' },
        { token: 'delimiter.bracket.embed', foreground: 'FACC15' },
    ],
    colors: {
        'editor.background': '#242424',
        'editor.foreground': '#e4e4e7',
        'editor.lineHighlightBackground': '#2d2d2d',
        'editorCursor.foreground': '#60a5fa',
        'editor.selectionBackground': '#3f3f46',
        'editorBracketMatch.background': '#3f3f4620',
        'editorBracketMatch.border': '#52525b',
    },
};

export const kirunLightTheme: MonacoEditor.editor.IStandaloneThemeData = {
    base: 'vs',
    inherit: true,
    rules: [
        { token: 'keyword', foreground: '8B5CF6', fontStyle: 'bold' },
        { token: 'keyword.control', foreground: 'F97316' },
        { token: 'type', foreground: '14B8A6', fontStyle: 'bold' },
        { token: 'type.identifier', foreground: '14B8A6', fontStyle: 'bold' },
        { token: 'entity.name.function', foreground: '10B981', fontStyle: 'bold' },
        { token: 'entity.name.tag', foreground: '64748B' },
        { token: 'variable.parameter', foreground: '3B82F6' },
        { token: 'variable.predefined', foreground: '06B6D4', fontStyle: 'bold' },
        { token: 'variable', foreground: '6366F1' },
        { token: 'identifier', foreground: '1a202c' },
        { token: 'number', foreground: '84CC16' },
        { token: 'number.float', foreground: '84CC16' },
        { token: 'string.value', foreground: 'F97316' },
        { token: 'string.expression', foreground: '14B8A6' },
        { token: 'string', foreground: 'F97316' },
        { token: 'string.escape', foreground: 'EAB308' },
        { token: 'string.invalid', foreground: 'F43F5E' },
        { token: 'comment', foreground: '94A3B8', fontStyle: 'italic' },
        { token: 'operator', foreground: '1a202c' },
        { token: 'delimiter', foreground: '1a202c' },
        { token: 'delimiter.bracket.embed', foreground: 'EAB308' },
    ],
    colors: {
        'editor.background': '#f5f7fa',
        'editor.foreground': '#1a202c',
        'editor.lineHighlightBackground': '#e8ecef',
        'editorCursor.foreground': '#3182ce',
        'editor.selectionBackground': '#cbd5e0',
        'editorBracketMatch.background': '#cbd5e020',
        'editorBracketMatch.border': '#a0aec0',
    },
};

export const kirunHighContrastTheme: MonacoEditor.editor.IStandaloneThemeData = {
    base: 'hc-black',
    inherit: true,
    rules: [
        { token: 'keyword', foreground: '00FFFF', fontStyle: 'bold' },
        { token: 'keyword.control', foreground: 'FFD700' },
        { token: 'type', foreground: 'FF00FF', fontStyle: 'bold' },
        { token: 'type.identifier', foreground: 'FF00FF', fontStyle: 'bold' },
        { token: 'entity.name.function', foreground: '00FF00', fontStyle: 'bold' },
        { token: 'entity.name.tag', foreground: 'FFFFFF' },
        { token: 'variable.parameter', foreground: 'FFFF00' },
        { token: 'variable.predefined', foreground: '00FFFF', fontStyle: 'bold' },
        { token: 'variable', foreground: 'ADD8E6' },
        { token: 'number', foreground: 'FFA500' },
        { token: 'number.float', foreground: 'FFA500' },
        { token: 'string.value', foreground: 'FF6347' },
        { token: 'string.expression', foreground: '00CED1' },
        { token: 'string', foreground: 'FFA500' },
        { token: 'comment', foreground: '808080', fontStyle: 'italic' },
        { token: 'operator', foreground: 'FFFFFF' },
        { token: 'delimiter', foreground: 'FFFFFF' },
    ],
    colors: {
        'editor.background': '#0a0a0a',
        'editor.foreground': '#ffffff',
        'editor.lineHighlightBackground': '#1a1a1a',
        'editorCursor.foreground': '#ffff00',
        'editor.selectionBackground': '#1a1a1a',
        'editorBracketMatch.background': '#ffff0030',
        'editorBracketMatch.border': '#ffff00',
    },
};

export const kirunEasyOnEyesTheme: MonacoEditor.editor.IStandaloneThemeData = {
    base: 'vs',
    inherit: true,
    rules: [
        { token: 'keyword', foreground: '9F7AEA', fontStyle: 'bold' },
        { token: 'keyword.control', foreground: 'ED8936' },
        { token: 'type', foreground: '38B2AC', fontStyle: 'bold' },
        { token: 'type.identifier', foreground: '38B2AC', fontStyle: 'bold' },
        { token: 'entity.name.function', foreground: '48BB78', fontStyle: 'bold' },
        { token: 'entity.name.tag', foreground: '6b6456' },
        { token: 'variable.parameter', foreground: '4299E1' },
        { token: 'variable.predefined', foreground: '0BC5EA', fontStyle: 'bold' },
        { token: 'variable', foreground: '667EEA' },
        { token: 'identifier', foreground: '3e3832' },
        { token: 'number', foreground: '9AE6B4' },
        { token: 'number.float', foreground: '9AE6B4' },
        { token: 'string.value', foreground: 'ED8936' },
        { token: 'string.expression', foreground: '38B2AC' },
        { token: 'string', foreground: 'DD6B20' },
        { token: 'comment', foreground: '6b6456', fontStyle: 'italic' },
        { token: 'operator', foreground: '3e3832' },
        { token: 'delimiter', foreground: '3e3832' },
    ],
    colors: {
        'editor.background': '#f4f1ea',
        'editor.foreground': '#3e3832',
        'editor.lineHighlightBackground': '#e8e4dc',
        'editorCursor.foreground': '#7c9885',
        'editor.selectionBackground': '#d4cfc4',
        'editorBracketMatch.background': '#d4cfc430',
        'editorBracketMatch.border': '#bfb9ab',
    },
};

export const kirunFlaredUpTheme: MonacoEditor.editor.IStandaloneThemeData = {
    base: 'vs-dark',
    inherit: true,
    rules: [
        { token: 'keyword', foreground: 'C084FC', fontStyle: 'bold' },
        { token: 'keyword.control', foreground: 'FB923C' },
        { token: 'type', foreground: '22D3EE', fontStyle: 'bold' },
        { token: 'type.identifier', foreground: '22D3EE', fontStyle: 'bold' },
        { token: 'entity.name.function', foreground: '4ADE80', fontStyle: 'bold' },
        { token: 'entity.name.tag', foreground: 'b19cd9' },
        { token: 'variable.parameter', foreground: '60A5FA' },
        { token: 'variable.predefined', foreground: 'F472B6', fontStyle: 'bold' },
        { token: 'variable', foreground: 'A78BFA' },
        { token: 'identifier', foreground: 'f0e7ff' },
        { token: 'number', foreground: 'FDE047' },
        { token: 'number.float', foreground: 'FDE047' },
        { token: 'string.value', foreground: 'FBBF24' },
        { token: 'string.expression', foreground: '2DD4BF' },
        { token: 'string', foreground: 'FB923C' },
        { token: 'comment', foreground: 'b19cd9', fontStyle: 'italic' },
        { token: 'operator', foreground: 'f0e7ff' },
        { token: 'delimiter', foreground: 'f0e7ff' },
    ],
    colors: {
        'editor.background': '#151226',
        'editor.foreground': '#f0e7ff',
        'editor.lineHighlightBackground': '#1f1b35',
        'editorCursor.foreground': '#a78bfa',
        'editor.selectionBackground': '#4a3f7a',
        'editorBracketMatch.background': '#4a3f7a30',
        'editorBracketMatch.border': '#6b5ba6',
    },
};

export function registerKIRunThemes(monaco: typeof MonacoEditor) {
    monaco.editor.defineTheme('kirun-dark', kirunDarkTheme);
    monaco.editor.defineTheme('kirun-light', kirunLightTheme);
    monaco.editor.defineTheme('kirun-high-contrast', kirunHighContrastTheme);
    monaco.editor.defineTheme('kirun-easy-on-eyes', kirunEasyOnEyesTheme);
    monaco.editor.defineTheme('kirun-flared-up', kirunFlaredUpTheme);
}
